/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const Button: typeof import('@mui/material')['Button']
  const Card: typeof import('@mui/material')['Card']
  const Carousel: typeof import('react-material-ui-carousel')['default']
  const Container: typeof import('@mui/material')['Container']
  const Divider: typeof import('@mui/material')['Divider']
  const IconButton: typeof import('@mui/material')['IconButton']
  const Image: typeof import('next/image')['default']
  const InputBase: typeof import('@mui/material')['InputBase']
  const Link: typeof import('next/link')['default']
  const List: typeof import('@mui/material')['List']
  const ListItemButton: typeof import('@mui/material')['ListItemButton']
  const ListItemText: typeof import('@mui/material')['ListItemText']
  const Paper: typeof import('@mui/material')['Paper']
  const React: typeof import('react')['default']
  const Tab: typeof import('@mui/material')['Tab']
  const Tabs: typeof import('@mui/material')['Tabs']
  const Tooltip: typeof import('@mui/material')['Tooltip']
  const createRef: typeof import('react')['createRef']
  const forwardRef: typeof import('react')['forwardRef']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const startTransition: typeof import('react')['startTransition']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ReactElement } from 'react'
  import('react')
}
