import type { Metadata, Viewport} from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import CssBaseline from '@mui/material/CssBaseline';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
const inter = Inter({ subsets: ["latin"] });

export const viewport: Viewport = {
	initialScale:1,
	width:"device-width"
}

export const metadata: Metadata = {
  title: "某公司",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
	  <CssBaseline />
      <body className={inter.className}>
	      <AppRouterCacheProvider>
	  <header>某公司</header>
	  {children}
+        </AppRouterCacheProvider>
</body>
    </html>
  );
}
